### ISSUE TITLE
Heterodyne instrument cleanup

### ISSUE THREAD

**Issue by antsr** [DiCarloLab-Delft/PycQED_py3#107]
The heterodyne meta-instruments for spectroscopy measurements look outdated. Is there some way of doing spectroscopy measurements? 

Current issues:
* The "LO_modulated_Heterodyne" (would Homodyne be a more appropriate name?) can not be used with the UHFQC.  
* What is the use of get_t_base for prepare()?
* The if-else structure for different acquisition instruments could be replaced by different subclasses derived from a common abstract class for a cleaner code
* As mentioned in the closed issue #22, the AWG channels are hardcoded, but it was unclear to me if the issue got solved.

I have fixed some of these issues in our JTestB branch. If there is no more recent way of doing these measurements, I suggest that I could clean up the file.

Also, I have a weakly related question: what is ATS?

**Comment by AdriaanRol** [comment]
Hi Ants, 

Good to hear from you, the HS is indeed a bit outdated but is perfectly functional for us. If you want to give it a good cleanup that is more than welcome. If you want to structurally change some things (and I think there may be some) it would be good to discuss them first. 

To answer your questions, 
> The "LO_modulated_Heterodyne" (would Homodyne be a more appropriate name?) can not be used with the UHFQC.
 
This is correct, I would love to use this with the UHFQC, as it makes sure phase information is also respected in resonator scans.  We had originally made this with an AWG5014 in mind. 

> What is the use of get_t_base for prepare()?

This is used for setting the integration weights in the CBox (our homebuilt FPGA). The timebase is relevant for determining the right samples in relation to the clock frequency (which is different depening on the acquisition instrument). 

> The if-else structure for different acquisition instruments could be replaced by different subclasses derived from a common abstract class for a cleaner code

We originally intended this to work with inheritance but have since found that switching the acquisition instrument provides more flexibility in our experiments. This is particularly useful when having a single setup in which we routinely switch between different readout configurations. Though I have to admit that the current version of these if statements does not look so nice. 

>  As mentioned in the closed issue #22, the AWG channels are hardcoded, but it was unclear to me if the issue got solved.

I don't believe it has. That being said, we do have an upgraded  [pulsed spectroscopy](https://github.com/DiCarloLab-Delft/PycQED_py3/blob/master/pycqed/measurement/pulse_sequences/single_qubit_tek_seq_elts.py#L22) sequence that uses parameters from the qubit object. We should make a similar sequence for the heterodyne, but have never needed it as the only requirement currently is to use a specific marker channel. 

That being said, if you plan to do anything with pulse sequences, take a look at the 2-qubit gates branch. I've made quite a few improvements and changes to the sequencer there. 

> Also, I have a weakly related question: what is ATS?

The ATS is an acquisition card by Alazar that we use quite extensively in our lab. We have not ported this to QCoDeS yet because we have the CBox and more recently the UHFQC, Niels is currently making an acquisition controller for the QCoDeS version of the ATS driver.

**Comment by antsr** [comment]
Having worked with the PycQED a bit more now, it seems to me that the  `HeterodyneInstrument` could be entirely reduced to a sweep function, that changes the frequencies of the readout LO and RF together keeping the difference of the IF, and an integrated average single datapoint soft detector. Would there be any arguments against this? However, since the current solution is working OK for us as well, there is no real reason to change it.

**Comment by AdriaanRol** [comment]
@antsr , again your observation is correct. In my personal opinion I would like to retire the heterodyne instrument and move some of the functionality to the qubit object. However, as you mention, the current solution works fine. As such making this change is quite a low priority. 

Also I'll close this issue as your PR #118 did a nice job of cleaning up a bit.
