### ISSUE TITLE
Not all parameters reload when using gen.load_settings_onto_instrument

### ISSUE THREAD

**Issue by elrama-** [DiCarloLab-Delft/PycQED_py3#138]
While reloading the qubit object parameters, the dac_channel parameter does not get reloaded.

Don't understand exactly why

**Comment by AdriaanRol** [comment]
This is an issue that has to do with the datatypes that are being saved in the snaphshot of the setup. Currently we save floats correctly and everything else get's saved as a string. When trying to load it from such a datafile, the types don't match and it will not correctly reload all settings. 

For the QCoDeS dataset I have implemented this correctly for all datatypes, however we have not switched over as that is still under construction. That being said, it should not be hard to port over.

**Comment by lciorciaro** [comment]
Since I am constantly reloading parameters which are lists when testing new things, it would really help me if they were correctly set with gen.load_settings_onto_instruments.
Fixing this for lists should not be hard, even if they are saved as strings. A string representation of a list can be safely evaluated like this:
`import ast`
`strList = '[1, 2, 3, "4", 5.0]'`
`x = ast.literal_evl(strList)`

**Comment by AdriaanRol** [comment]
@lciorciaro . Let's fix this tomorrow, it's increasingly important in relation to the frequent reloading for the demo.

**Comment by AdriaanRol** [comment]
Tested solution on enh/data_saving branch. Works fine but new saving method does not work for numpy data types.
