### ISSUE TITLE
Old unusable code

### ISSUE THREAD

**Issue by antsr** [DiCarloLab-Delft/PycQED_py3#144]
In several places I have found features that do not seem to work or be used anymore. For better code readability it would be best to remove the parts that are broken and are not planned to be used in the future from the library. The classes or modules that I have found that might fall into this category are
* Detector functions using the `qt` library
  * `TimeDomainDetector`
  * `VNA_Detector`
  * `VNA_ATT_Detector`
  * `PulsedSpectroscopyDetector`
  * `RS_FSV_fixed_frequency`
* Cbox(not v3) detector functions
* `measurement/pulse_sequences/spectroscopy_seqs.py`
* `measurement/chevron_olli.py` (superseded by `simulations/chevron_sim.py`)
* `IQ_mixer` that is only referenced by code in `measurement/archived`
* `measurement/distortions_RT.py`
* `measurement/distortions_models.py`

**Comment by AdriaanRol** [comment]
@antsr I completely agree that deprecated code should be deleted. The hardest part is coming up with the list, which you have kindly started with. 

I usually go forward by just silently deleting or "cleaning" old code (*bad*). I think the best way to move forward is to do this through a PR (so that people can complain if we break something). 

Let's go over the list 
- Detector functions with `qt` -> yes we should delete these 
- CBox (not v3) detector functions -> we should not delete these, it's a piece of hardware that we still use 
- spectroscopy seqs -> still used in the qubit object (quite extensively even) we have a newer way of doing this but this still works and is in use. 
- chevron olli -> Yes, we should delete this @elrama-  is this OK ? 
- IQ_mixer object -> not sure, we're indeed not using it but I'd like to keep it around for awhile until we have the proper final solution to devices containing many elements. 
- distortions_RT -> AFAIK this is still used quite extensively in the RT part of the calibrations but I should check with @elrama- 
- distortions_models -> this is all part of the kernel object but again checking with @elrama- to be sure.

**Comment by AdriaanRol** [comment]
Closing this issue as this is a general problem/point of interest and not a specific issue we can (ever) close.
