### ISSUE TITLE
AWG nr 1 plays wrong codeword pulse 

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#162]
@gtaifu 
Steps to reproduce 

- upload qumis file defined below that plays codeword pulse 1 on awg 1 
- Put awg 1 output 0 ( I channel) on the scope 
- Change the waveform with the following python snippet. You will see that the waveform that changes corresponds to codeword 5. 

Note that the other AWGs do work as expected. 

``` python 
awg_nr = 1
codeword_idx = 1
I_ch = 0
I_wave = np.ones(10)
CBox.set_awg_lookuptable(awg_nr, codeword_idx, I_ch, I_wave)
```

Qumis file 
```
mov r0, 20000   # r0 stores the cycle time , 100 us 
mov r1, 0       # sets the inter pulse wait to 0
mov r14, 0      # r14 stores number of repetitions
# Experiment: repeat the rounds for infinite times
wait 1 
Exp_Start: 

WaitReg r0 
WaitReg r0 
pulse 0000 1001 0000 
wait 10
wait 200 
trigger 0000001, 2
wait 558 
beq r14, r14, Exp_Start       # Infinite loop
```

**Comment by jacobdesterke** [comment]
Tested on CBox firmware v3.3.5 and the problem wasn't reproducible.

Tested with all AWGs loaded with cos with incremented number of periods in combination with the following Qumis program that triggers all codewords:

```
mov r0, 20000   # r0 stores the cycle time , 100 us 
mov r1, 0       # sets the inter pulse wait to 0
mov r14, 0      # r14 stores number of repetitions
# Experiment: repeat the rounds for infinite times
wait 1 
Exp_Start: 

#WaitReg r0 
WaitReg r0 
trigger 0000001, 2
wait 5

pulse 1000 1000 1000
wait 160
pulse 1001 1001 1001
wait 160
pulse 1010 1010 1010 
wait 160
pulse 1011 1011 1011 
wait 160
pulse 1100 1100 1100 
wait 160
pulse 1101 1101 1101 
wait 160
pulse 1110 1110 1110 
wait 160
pulse 1111 1111 1111 
wait 160

wait 598 
beq r14, r14, Exp_Start       # Infinite loop
```

This shows:
![ds4_quickprint11](https://user-images.githubusercontent.com/10159480/32172419-cfd58f26-bd7b-11e7-924b-7523cc5b0f5b.png)

After running the python snippet the output shows:
![ds4_quickprint12](https://user-images.githubusercontent.com/10159480/32172459-f3b42b6e-bd7b-11e7-87e3-00ad21d42430.png)

Closed the issue since the firmware version that had this problem is not documented and the current firmware version (v3.3.5) doesn't show this problem.
