### ISSUE TITLE
Label/units of qubit frequency in spectroscopy analysis is wrong 

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#386]
### Steps to reproduce
1. Run analysis on spectroscopy data 
### Expected behaviour
I would expect the units of the analysis to be correct. 

### Actual behaviour
It is not correct 
![source frequency distance](https://user-images.githubusercontent.com/6142932/32242025-fa908350-be71-11e7-9a61-9c114d6370ce.png)

Note that the value extracted from the analysis is correct. 
### System
This includes the recent ETH analysis update. 

**Proj/NovDemo**

**5668bf39166b2e6fea22c7929ccb6ea15de8fdb6**

@antsr @Vintrix I'm tagging you because maybe you know more. In any case this should be pretty straightforward to fix.

**Comment by Vintrix** [comment]
@AdriaanRol thanks for tagging me in this issue. Indeed there was a little bug on my part in the enhancement/analysis_v1_peak_finder PR; I apologize about that. But it is a quick fix. 

In the DCL master version, in measurement_analysis.py: 
* line 4927:   x_unit=self.sweep_unit   --->   x_unit=self.sweep_unit[0]
* line 4957:   unit=self.sweep_unit      --->   unit=self.sweep_unit[0]
Since this unit was incorrectly retrieved, the set_xlabel function did not receive the correct units. 

Should I make a new PR with these 2-line changes?

**Comment by AdriaanRol** [comment]
@Vintrix yes, that would be greatly appreciated.
